cache: packages
sudo: required
warnings_are_errors: false
services:
  - docker
before_install:
# Set up environment and create required images
-  docker-compose run rdata
script:
# Load packages and install the required packages
# Install retriever from source and run tests 
-  docker-compose  run rdata Rscript load_and_test.R || exit 1
