language: r
cache: packages
sudo: required
warnings_are_errors: false
r_packages:
  - covr
  - RPostgreSQL
  - DBI
  - testthat

services:
  - postgresql
addons:
  postgresql: "9.4"
  apt:
    packages:
      - sqlite3
      - r-cran-testthat
      - r-cran-dbi
      - r-cran-rpostgresql
      - r-cran-rmysql
      - r-cran-rsqlite
      - r-cran-devtools

before_install:
  - export PATH=$(which python$R_PYTHON_VERSION):$PATH
  - export PYTHON=$(which python$R_PYTHON_VERSION)
  - export PYTHONPATH=$(which python$R_PYTHON_VERSION):$PYTHONPATH
  - export RETICULATE_PYTHON=$PYTHON
  - R_PATH="PATH=$PATH" | echo $R_PATH >  ~/.Renviron
  - R_RETICULATE_PYTHON="RETICULATE_PYTHON=$PYTHON" | echo $R_RETICULATE_PYTHON >>  ~/.Renviron

before_script:
  - psql -c 'create database testdb;' -U postgres

install:
  - R -e 'devtools::install_deps(dep = T)'
  - R -e 'devtools::install_github("klutometis/roxygen")'
  # - R -e 'install.packages(c("reticulate"), dependencies=TRUE)'
  - R -e 'devtools::install_github("rstudio/reticulate")'
  - R -e 'library(reticulate)'

  # install Retriever python library
  - git clone https://github.com/weecology/retriever.git retriever
  - cd retriever
  - wget https://bootstrap.pypa.io/get-pip.py
  - sudo $PYTHON get-pip.py
  - rm -rf get-pip.py
  - sudo $PYTHON -m pip install -r requirements.txt
  - sudo $PYTHON -m pip install pytest-cov -U
  - sudo $PYTHON -m pip install pytest-xdist -U
  - sudo $PYTHON -m pip install  . -U
  - cd ..
  - rm -rf retriever/
  - sudo rm -rf ~/.retriever
  # Exports
  - export PYTHON_CONFIG=python${R_PYTHON_VERSION}-config
  - export PKG_LIBS=`$PYTHON_CONFIG --ldflags`
  - export PKG_CPPFLAGS=`$PYTHON_CONFIG --includes`
  - export PKG_CPPFLAGS+=" -D PYTHONLIBFILE=\\\"libpython${R_PYTHON_VERSION}.so\\\""
# database setup
before_script:
  - sqlite3 --version
  - psql -c 'create database testdb;' -U postgres
script:
  - R CMD build .
  - R CMD check *tar.gz
  - R -e 'library(testthat)'
  #- R -e 'library(reticulate); rt <- import("retriever"); rdataretriever::datasets()'
  - R -e 'library(devtools);devtools::test()'
